# Pytorch Essentials

In [98]:
import torch

print(torch.cuda.is_available())

False


# Tensors

- Data structure that is very similar to arrays and matrices. Used to encode the inputs and outputs of a model.
- Similar to ndarray from numpy but can use hardware accelaration on GPU or similar.
- Optimized for automatic differentiation.

In [99]:
import numpy as np
import torch

data = [[1, 2], [3, 4]]
numpy_data = np.array(data)
tensor_data = torch.tensor(data)

print("Data:\n", data)
print("Numpy:\n", numpy_data)
print("Tensor:\n", tensor_data)

Data:
 [[1, 2], [3, 4]]
Numpy:
 [[1 2]
 [3 4]]
Tensor:
 tensor([[1, 2],
        [3, 4]])


Different ways to create a tensor

In [100]:
shape = (5,1)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

Random Tensor: 
 tensor([[0.5621],
        [0.3576],
        [0.2275],
        [0.6045],
        [0.1647]]) 

Ones Tensor: 
 tensor([[1.],
        [1.],
        [1.],
        [1.],
        [1.]]) 

Zeros Tensor: 
 tensor([[0.],
        [0.],
        [0.],
        [0.],
        [0.]])


Creating a tensor from numpy or another tensor

In [101]:
import numpy as np
import torch

data = np.array([[1,2,3,4]])
tensor = torch.from_numpy(data)
print("Tensor:\n>", tensor)

tensor_copy = torch.full_like(tensor, fill_value=0.1, dtype=torch.float)
print("Tensor:\n>", tensor_copy)

tensor_copy = torch.rand_like(tensor,  dtype=torch.float)
print("Tensor:\n>", tensor_copy)

tensor_copy = torch.ones_like(tensor)
print("Tensor:\n>", tensor_copy)

tensor_copy = torch.zeros_like(tensor)
print("Tensor:\n>", tensor_copy)

Tensor:
> tensor([[1, 2, 3, 4]])
Tensor:
> tensor([[0.1000, 0.1000, 0.1000, 0.1000]])
Tensor:
> tensor([[0.7525, 0.6842, 0.1418, 0.2094]])
Tensor:
> tensor([[1, 1, 1, 1]])
Tensor:
> tensor([[0, 0, 0, 0]])


Displaying the different attributes of a tensor.

In [102]:
tensor = torch.rand(3,4)

print(f"Data of tensor:\n{tensor.data}")
print(f"Shape of tensor:            {tensor.shape}")
print(f"Datatype of tensor:         {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Data of tensor:
tensor([[0.9285, 0.8429, 0.5046, 0.6273],
        [0.2022, 0.6411, 0.2038, 0.9237],
        [0.1260, 0.4717, 0.6614, 0.5908]])
Shape of tensor:            torch.Size([3, 4])
Datatype of tensor:         torch.float32
Device tensor is stored on: cpu


Slicing tensors (just like in numpy)

In [103]:
tensor = torch.ones(4, 4)
print(f"First row: {tensor[0,:]}")
print(f"First column: {tensor[:, 0]}")
print(f"Last column: {tensor[..., -1]}")
tensor[1:-1,1:-1] = 0
print(tensor)

First row: tensor([1., 1., 1., 1.])
First column: tensor([1., 1., 1., 1.])
Last column: tensor([1., 1., 1., 1.])
tensor([[1., 1., 1., 1.],
        [1., 0., 0., 1.],
        [1., 0., 0., 1.],
        [1., 1., 1., 1.]])


Joining tensors together

In [104]:
tensor = torch.rand((2,2))
t1 = torch.cat([tensor, tensor, tensor], dim=0)
print(t1)
t2 = torch.cat([tensor, tensor, tensor], dim=1)
print(t2)

tensor([[0.8925, 0.1288],
        [0.3533, 0.8492],
        [0.8925, 0.1288],
        [0.3533, 0.8492],
        [0.8925, 0.1288],
        [0.3533, 0.8492]])
tensor([[0.8925, 0.1288, 0.8925, 0.1288, 0.8925, 0.1288],
        [0.3533, 0.8492, 0.3533, 0.8492, 0.3533, 0.8492]])


Arithmetical operations can be done different ways.

In [105]:
tensor = torch.rand((2,2))

# This computes the matrix multiplication between two tensors. y1, y2, y3 will have the same value
# ``tensor.T`` returns the transpose of a tensor
y1 = tensor @ tensor.T
y2 = tensor.matmul(tensor.T)
y3 = torch.rand_like(y1)
torch.matmul(tensor, tensor.T, out=y3)
print(y1)
print(y2)
print(y3)

print()
# This computes the element-wise product. z1, z2, z3 will have the same value
z1 = tensor * tensor
z2 = tensor.mul(tensor)
z3 = torch.rand_like(tensor)
torch.mul(tensor, tensor, out=z3)
print(z1)
print(z2)
print(z3)

tensor([[0.2011, 0.1271],
        [0.1271, 0.1041]])
tensor([[0.2011, 0.1271],
        [0.1271, 0.1041]])
tensor([[0.2011, 0.1271],
        [0.1271, 0.1041]])

tensor([[0.1426, 0.0585],
        [0.1035, 0.0005]])
tensor([[0.1426, 0.0585],
        [0.1035, 0.0005]])
tensor([[0.1426, 0.0585],
        [0.1035, 0.0005]])


Single-element tensors If you have a one-element tensor, for example by aggregating all values of a tensor into one value, you can convert it to a Python numerical value using item():

In [106]:
agg = tensor.sum()
agg_item = agg.item()
print(agg_item, type(agg_item))

0.9644578695297241 <class 'float'>
